config:
  configVersion: 4
application:
  shortName: ZTWIM-Operator-ZAP
  url: https://api.ci-ln-ffm7hwb-72292.gcp-2.ci.openshift.org:6443
general:
  authentication:
    type: http_header
    parameters:
      name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJMNUVuV3RuamJ4U1lwLUJDTUZOVGw1c3E1S3ZFLWRTOFNtRDZGS1gtQ0UifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc3Mzk4NTI0NywiaWF0IjoxNzczOTgxNjQ3LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiJlMTk3OTQyMy0zZDQyLTQ3NjktYjUzMS1kNzY4MGI4YWI5ZmEiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImRlZmF1bHQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZGVmYXVsdCIsInVpZCI6ImIxOTFhNDgxLTYyNjYtNDQ5My04OGQ0LTY4YmQyNDU5NTBhZiJ9fSwibmJmIjoxNzczOTgxNjQ3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpkZWZhdWx0In0.aif3KnJv4lBEkTMbV1B3S9AL77u_7YBOOFTPiCPo3429koBpNcO7rc2bvQ5lFG_b6IaYRC76rtSTbeJXDjKdc0q9VQpO9_Utcz0W9pE-fylbCqblMsQ93PDqWUMQ0o5HTWC_urLefGwsvPWS0kSgFAgL2PHuCa5CfQ6LS0-FmYe1_eBUpmJSGzEDpZBIdbwTup5qh2zBO4V9whZHZxpr_ssWVftOSPXCafE54Q6_fxe74VsAHYSh1c9UvRq_lzL5tW98ZQkpDnkjoEaawgYXRZPtW15Y29uOAu1nPtRmVr5C8-ClnsQFGWh12CyAPbe0vW-FqA2Gc7l2pOmtIniCVUku_G-i9uM6aLXml08G1-NPI5BgVjMyq8vG7pe9HhtmaEiCRV55np_LHboSWdqW4Gq-28ze9wNJWNK-JMXDiwHmB3SHkcSN1kZVM7CtAaX0IBBNBXVnmp3h2qD4vGeM4WrpIT40NlFlEirCjXoUhOD7zELL70da-6wkr4srCr8TxlC5NlSgsITy5VsAlUU1jasH0r6-qAkLVAx_DydpcukzJc8Beu-1houVZQk7ztsJQI6irSCjAawuGGQOB2uYA5xIuxEbLpxnq0l1Lqa3rRKUCN2EQA7S2Aud-BfP6z5J2St8tD9_89fVNaHtKG3V2GIJzNbDUl95apuzlfq6gOA
  container:
    type: none
scanners:
  zap:
    apiScan:
      apis:
        apiUrl: https://api.ci-ln-ffm7hwb-72292.gcp-2.ci.openshift.org:6443/openapi/v3/apis/operator.openshift.io/v1alpha1
    passiveScan:
      disabledRules: 2,10015,10027,10096,10024,10098,10023
    activeScan:
      policy: Kubernetes-API-scan
    report:
      format:
      - json
      - html
    miscOptions:
      updateAddons: false
